<?php

/**
 * Implements hook_menu()
 **/
function date_to_now_menu() {
  $items = array();

  $items['system/date_to_now'] = array(
    'access arguments' => array('access date to now field'),
    'page callback'    => '_date_to_now_system_callback',
    'file'             => 'includes/date_to_now.pages.inc',
    'type'             => MENU_CALLBACK,
  );

  return $items;
} // end function date_to_now_menu

/**
 * Implements hook_permission()
 **/
function date_to_now_permission() {
  return array(
    'access date to now field' => array(
      'title' => t('Access the "Set to Now" field'),
    ),
  );
} // end function date_to_now_permission

/**
 * Implements hook_theme
 **/
function date_to_now_theme($existing, $type, $theme, $path) {
  return array(
    'date_to_now' => array(
      'variables' => array(
        'node' => NULL,
      ),
      'template' => 'templates/date_to_now',
    ),
  );
} // end function date_to_now_theme

/**
 * Implements hook_node_view()
 **/
function date_to_now_node_view($node, $view_mode, $langcode) {
  if (_date_to_now_is_allowed($node->type) && user_access('access date to now field')) {
    $fields = _date_to_now_get_fields($node->type);
    drupal_add_js(drupal_get_path('module', 'date_to_now') .'/js/ajax.js');
    foreach ($fields as $field) {
      $mode = isset($field['display'][$view_mode]) ? $view_mode : 'default';
      if ($field['display'][$mode]['type'] !== 'hidden') {
        // Display the link
        $node->content[$field['field_name'] .'_date_to_now'] = array(
          '#markup' => theme('date_to_now', array('node' => $node, 'field_name' => $field['field_name'])),
          '#weight' => $node->content[$field['field_name']]['#weight'] + .1,
        );
      } // end if ($field['display'][$view_mode]['type'] !== 'hidden')
    } // end foreach ($fields as $field)
  } // end if (_date_to_now_is_allowed($node->type) && user_access('access date to now field'))
} // end function date_to_now_node_view

/**
 * Determine whether a node is allowed to display the date_to_now pseudo field
 * @param string $node_type Type of the Node being checked
 * @return boolean
 **/
function _date_to_now_is_allowed($node_type) {
  return count(_date_to_now_get_fields($node_type)) > 0;
} // end function _date_to_now_is_allowed

/**
 * Get the fields provided by the date module
 * @param string $node_type Node Type
 * @return array Array of fields that are provided by the date module
 **/
function _date_to_now_get_fields($node_type) {
  $fields = field_info_instances('node', $node_type);
  return array_filter($fields, '_date_to_now_filter_field_instances');
} // end function _date_to_now_get_fields

/**
 * Callback for array_filter to determine whether a field is a date field
 * @param mixed $var Array element to check
 * @return boolean
 **/
function _date_to_now_filter_field_instances($var) {
  return $var['widget']['module'] == 'date';
} // end function _date_to_now_filter_field_instances
